### ISSUE TITLE
State of project

### ISSUE THREAD

**Issue by manicai** [jkeylu/torngithub#1]
Hi,

I am going to start using this is in a couple of projects but make some changes to get it to work with Tornado 4. Was wondering if you still had an interest in this after three years and would want pull requests or whether you'd prefer to pass on the maintenance?

Regards,
Ian

**Comment by jkeylu** [comment]
I have been busy with work recently. If you are willing to continue to
maintain this project, I can add you as collaborator.

2016-11-22 20:06 GMT+08:00 Ian Glover <notifications@github.com>:

**Comment by manicai** [comment]
Hi,

Thanks. I have tidied up my changes and sent them as a pull request if you want to have a look. Am happy to be added, or just send pull requests as you prefer. 

Cheers,
Ian
